### PR TITLE
Testing Eric's branch

### PR DESCRIPTION
**Pull request by mattipee**
After some code cleansing, I did some testing.

### CODE REVIEW

**Comment by mattipee** [comment]
@ericchristoffersen Before I merge this, worth a discussion here. Ignore the fix to calibration speed.

I disabled both your and Wouter's routine, and started in ERG mode.

I gradually increased load, 100, 150, 200, 220, 250, or something.

For each set-point, I got the wheel speed high enough, then set the load, then started slowing down until I detected stuttering from the motor. Each time I detected stuttering, I noted the force in N and the speed in m/s, which I was printing out. (Edit: I realise now all I needed was the power I'd set, and the speed at which it starts stuttering... no need to capture force itself)

I graphed them on an x/y scatter, and it was more or less linear (give or take my eyeball-measurement error).

I divided the force in N by the speed in m/s*2 and got what appeared to be a constant... 10.

So I implemented the routine and set the threshold to 9. The result is rather good.

Are we talking torque here or something? I'll post my graph and numerical analysis in a second...

**Comment by mattipee** [comment]
image

image

**Comment by mattipee** [comment]
OK, not quite linear, but read 75N as 72, and 80N as 78, and it's pretty straight. :)

And by "merge", I mean get the concept into the ErgoSlope branch, rather than accept as default, despite which lines are or aren't commented in this PR. It's as valid as any, empirically. Less stuttering than Wouter's routine. It could be tested through FortiusANT as there's perhaps a larger user-base capable to quick-test a change like this.

Doesn't matter if it's final or flawed, I'll likely merge it to capture it, just thought it worth a discussion here rather than adding to the main PR comments.

**Comment by ericchristoffersen** [comment]
Terrific that you are measuring stuff. Facts. I'd like to see more data points, especially at the low end from 2-4kph.

N/v^2 is sort of a strange thing. Force and Watts I could understand being linear but I don't know what that thing is. That is weird so you need more data.

The other thing is to find if there might be some sort of overheating that their graphs are protecting against.

**Comment by mattipee** [comment]
> Terrific that you are measuring stuff. Facts. I'd like to see more data points, especially at the low end from 2-4kph.
> 
> N/v^2 is sort of a strange thing. Force and Watts I could understand being linear but I don't know what that thing is. That is weird so you need more data.
> 
> The other thing is to find if there might be some sort of overheating that their graphs are protecting against.

Very little happens at the very low end, the wheel just starts spinning... I'll have to be very ginger. You did mean 2-4**kph**, I hope? I've been testing in m/s, because it fits with the calcs. If you meant 4m/s, and if we think the Fortius is alike with the iGenius at ~118N, that'd mean teasing the wheel speed down gently at 470W+.

But I will repeat testing for more data, absolutely. Perhaps with a coffee and a banana.

Edit: my initial value of "10" and an assumption of 118N would give upper end of test range as sqrt(118/10) ~= 3.44 m/s, at @~405W.

**Comment by ericchristoffersen** [comment]
> > Terrific that you are measuring stuff. Facts. I'd like to see more data points, especially at the low end from 2-4kph.
> > N/v^2 is sort of a strange thing. Force and Watts I could understand being linear but I don't know what that thing is. That is weird so you need more data.
> > The other thing is to find if there might be some sort of overheating that their graphs are protecting against.
> 
> Very little happens at the very low end, the wheel just starts spinning... I'll have to be very ginger. You did mean 2-4**kph**, I hope? I've been testing in m/s, because it fits with the calcs. If you meant 4m/s, and if we think the Fortius is alike with the iGenius at ~118N, that's 470W+.
> 
> But I will repeat testing for more data, absolutely. Perhaps with a coffee and a banana.

Yes I meant kph. Could also be the limit is too low there to measure well and then it doesn't matter.

Could be the tacx limits were of the brake, not brake and wheel friction? How many different devices are called 'fortius'? Do any of those graphs apply to the fortius driver?

**Comment by mattipee** [comment]
With my initial value of "10" and an optimistic assumption of equivalence with the iGenius, 118 N would give upper end of test range as sqrt(118 N / 10) ~= 3.44 m/s, which would be 3.44 m/s * 118N =~405 W.

image

3.4 m/s == 12.24 kph. Perhaps coincidence, but the crossing point for 400W looks very close to that. So my working hypothesis is that it's "worse than the graph" below 3.4 m/s, and follows the graph above that. And follows my formula below.

image

Who knows. More data...

**Comment by mattipee** [comment]
> Could be the tacx limits were of the brake, not brake and wheel friction? How many different devices are called 'fortius'? Do any of those graphs apply to the fortius driver?

I don't know... I've seen 1000W quotes, also short duration sprints higher than that. It's certainly one of the more capable models-of-old, or at least I get that impression. Folk at FortiusANT might know. I'll wait until I've done data capture and then take this to them.

**Comment by ericchristoffersen** [comment]
> With my initial value of "10" and an optimistic assumption of equivalence with the iGenius, 118 N would give upper end of test range as sqrt(118 N / 10) ~= 3.44 m/s, which would be 3.44 m/s * 118N =~405 W.
> 
> image
> 
> 3.4 m/s == 12.24 kph. Perhaps coincidence, but the crossing point for 400W looks very close to that. So my working hypothesis is that it's "worse than the graph" below 3.4 m/s, and follows the graph above that. And follows my formula below.
> 
> Who knows. More data...

Here is your data as power for kph:

image

Need lots more data or stick with igenius graph.

**Comment by mattipee** [comment]
Also... if I want to test very low speeds, I may need to set the calibration value low. Typically, during calibration at 20kph, I get raw values in the order of -950 to -1200, depending of tyre pressure, temperature and how long I let it run. That's 7-9N, or 40-50W at 20 kph.

So for really low speeds, I may to eliminate any calibrated offset. I guess that will mean the reported force values are wrong, but I think I care more about what is commanded and when it fails. Hmmm...

Also raises the thought whether calibration value should be a function of wheel speed, or whether the Fortius unit knows what to do with the single value having been determined at 20kph. I have no power meter to play with that idea.

**Comment by mattipee** [comment]
> Here is your data as power for kph:
> 
> image
> 
> Need lots more data or stick with igenius graph.

It pains me slightly to graph against kph, but in order to draw a comparison with TACX's graph...

image

**Comment by mattipee** [comment]
@michelrdagenais feeling my way through this one, and more data to capture, but appreciate your input on the above.

**Comment by ericchristoffersen** [comment]
> It pains me slightly to graph against kph, but in order to draw a comparison with TACX's graph...

Why this yuge discrepency? You are setting erg mode manually and finding the 'fail' power for each speed? Could it be that their graph was just for the motor and you're getting tire slip? Because your data is real! 👍

**Comment by mattipee** [comment]
> > It pains me slightly to graph against kph, but in order to draw a comparison with TACX's graph...
> 
> Why this yuge discrepency? You are setting erg mode manually and finding the 'fail' power for each speed? Could it be that their graph was just for the motor and you're getting tire slip? Because your data is real! 👍

Setting ERG mode manually and finding the fail speed for each power.

I was getting some tyre slippage >350W at one point, it was pretty glazed so I ran calibration to spin it up and took some sandpaper to it. Tyre wasn't slipping for this data capture, no.

**Comment by mattipee** [comment]
Of course, it would be easier to nobble the code to set a constant force and then find the fail speed. That way I'm not fighting ERG mode at low cadence (spiral of death).

**Pull request merged**
